apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: v7n7rebk5-go 
  janus-idp.io/tekton: v7n7rebk5-go
  backstage.io/kubernetes-id: v7n7rebk5-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v7n7rebk5-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  